### ISSUE TITLE
Dependabot einrichten

### ISSUE THREAD

**Issue by jan-christiansen** [HS-Flensburg-PLTP/HS-Flensburg-PLTP.github.io#1]
Die Jekyll-Projekte, die ich nutze haben in ihren Abhängigkeiten immer wieder Sicherheitslücken. Ich erhalte vom GitHub-Dependabot dann Mail mit der Information. Wenn ich mich nicht irre, kann man sich auch direkt einen Pull Request erstellen lassen. Bitte einmal nachforschen und mir entsprechend Rückmeldung geben.

**Comment by klassiker** [comment]
Die möglichen Konfigurationen und die Aktivierung werden hier beschrieben: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

Ich empfehle die Option `Grouped` zu verwenden, um die Anzahl der Pull-Requests und Mails gering zu halten. Die Standard-Option wird dann automatisch mit aktiviert. Hier als Gesamtbild: ![Image](https://github.com/user-attachments/assets/deb41993-f244-414b-8e1b-b03419c1e92d)

**Comment by jan-christiansen** [comment]
Ich möchte eigentlich gerade verhindern, dass ich mir das selbst durchlesen muss. Mach doch bitte mal einen Vorschlag für eine sinnvolle Konfiguration.

**Comment by klassiker** [comment]
Ich verstehe nicht ganz. Wie soll es sich denn anders verhalten, als es das nach der Aktivierung entsprechend des zweiten Absatzes tut?

Oder anders gesagt, wenn ich die Frage richtig verstehe: Ich empfehle es so zu konfigurieren, dass es als `Grouped`-Update durchgeführt wird. Mehr gibt es da nicht einzustellen. Der Link war nur falls zusätzliche Informationen gewünscht sind, z.B. bzgl. der Einstellung in Bezug auf den Dependency graph o.Ä..
